### ISSUE TITLE
Fulfilment Website - Webpages Editing

### ISSUE THREAD

**Issue by AW-Martina** [inikoo/aiku#1529]
Adding Blocks ISSUES:

- [x] Can’t add text when selecting Text in Columns, It only allows me to add text to last column. 
- [x] Can’t upload picture into text box - it’s pending not uploading
- [x] Cant edit text on  CTA above the button
- [x] Can't upload images
- [x] Can't edit text above picture - Showcase (Bento Grid)
- [x] Can't add banners - when pressing create banner or banners gallery nothing happens
- [x] No option to move the picture or to align it to left/center/right 

![Image](https://github.com/user-attachments/assets/f7a8ad19-c979-4111-a8a8-d305c0d38baa)
![Image](https://github.com/user-attachments/assets/5c62ebc2-48fd-4c61-a4a9-e92a86fa1a53)
![Image](https://github.com/user-attachments/assets/cdcd043b-f01e-477f-aebd-c16e180c03df)
![Image](https://github.com/user-attachments/assets/be16922e-9e94-4832-8a0e-ce39d66273d5)
![Image](https://github.com/user-attachments/assets/796ace78-0935-4f90-8e0d-f1a7f81014e0)
![Image](https://github.com/user-attachments/assets/3c5edeab-23d4-4ecc-a0d2-c135a03a7bd1)
![Image](https://github.com/user-attachments/assets/a9ee8442-dab6-46d3-bab8-2f8372f74e48)

**Comment by YudhistiraA** [comment]
Hello @AW-Martina,

I have fixed this issue. You can test it again, and if you encounter any errors or bugs, try deleting the block and adding it again. There's a possibility that old website data is conflicting with that block.

Let me know if you face any other problems.

Best regards,
Arya

**Comment by AW-Martina** [comment]
Hi Arya, I still have a problem uploading pictures in the text box. I select the image and then it says just pending but its not uploading. Can you please have a look into this. Thank you.

![Image](https://github.com/user-attachments/assets/cc0c852c-fb62-4420-8aeb-9322d365f429)

**Comment by YudhistiraA** [comment]
hello @AW-Martina 

sorry for the problem you are facing, I have fixed the error you can try again

best regards,
Arya

**Comment by AW-Martina** [comment]
Hi Arya. 
Can you please add more options to the pricing blog? Such as: 

- [ ] - The background colour of the blog 
- [ ] - The background colour of individual cards
- [ ] - Editable subtitle text 
- [ ] - The colour of the description text is not working 
- [ ] - Editable button - text and colour 

Thank you 

![Image](https://github.com/user-attachments/assets/be820723-f778-483a-ab12-1f5cf178d17a)
