### ISSUE TITLE
pricing blog

### ISSUE THREAD

**Issue by YudhistiraA** [inikoo/aiku#1565]
> Hi Arya. 
> Can you please add more options to the pricing blog? Such as: 
> 
> - The background colour of the blog 
> - The background colour of individual cards
> - Editable subtitle text 
> - The colour of the description text is not working 
> - Editable button - text and colour 
> 
> Thank you 
> 
> ![Image](https://github.com/user-attachments/assets/be820723-f778-483a-ab12-1f5cf178d17a) 

 _Originally posted by @AW-Martina in [#1529](https://github.com/Inikoo-Ltd/aiku/issues/1529#issuecomment-2748094891)_

**Comment by dandiAW** [comment]
hi @AW-Martina  

I have fixed this issue. You can test it again and if you encounter any errors or bugs, try deleting the block and adding it again. There's a possibility that old website data is conflicting with that block.

Let me know if you face any other problems.

Best regards,
Dandi

**Comment by AW-Martina** [comment]
Hi @dandiAW 
Thank you, everything works fine now. Just one more thing, can the colour of the ticks, title and the most popular batch be editable. Also could there be a option to hide/display the batch - "most popular"
Thank you very much,
Martina

![Image](https://github.com/user-attachments/assets/fdec1926-7d7d-42c4-97df-b9f64b110780)

**Comment by dandiAW** [comment]
Hello @AW-Martina  Thank you for your response; I am pleased to hear your feedback. Regarding your request, I am currently working on it, and I will inform you as soon as everything is completed.

Additionally, if you have any further requests regarding a webpage block, please feel free to notify me by creating an issue or by writing directly about your request for a web block in hare.

Thank you for your attention.

Best regards,
Dandi

**Comment by AW-Martina** [comment]
Hi @dandiAW,

Thank you :) 
I will be adding things here as I work on the website, if that's ok :) Thank you 

- [x] - For the price block, can the price (/month) be optional and editable so we can turn it on/off or change it, please? 

 ![Image](https://github.com/user-attachments/assets/2003656d-9d17-4dbe-b145-a59001747a97)

- [ ] - Also, can there be an option to align text to the middle (price block) and add a picture/icon above the tile?

![Image](https://github.com/user-attachments/assets/955cf702-6713-4aad-8b5b-9ee747cfdfee)

- [ ] - Can as many things as possible be editable in the price block, please? The screenshot shows what I would like to re-create for our fulfilment.
![Image](https://github.com/user-attachments/assets/b43e50fb-c262-43b8-9b1d-9b3a5658864d)

- [x] - For the table in the text box, can the colour or the table borders be editable with a transparent option as well, please?
![Image](https://github.com/user-attachments/assets/46dd9f83-6a02-4f3a-aef9-658490019fb0)

- [x] - For the text in columns, can the margin (gap) between the columns be adjustable, please?
![Image](https://github.com/user-attachments/assets/6f6177c9-9d8e-406a-bee1-3ee98b0b12a9)

- [ ] - Can there be an option to have wrap text around the picture with options as in the picture in the text box, please?
![Image](https://github.com/user-attachments/assets/1367d1d7-7c65-41fa-a593-d2343f401afd)

- [x] - CTA button, can the width of the background be editable to be narrower so the button could be used just as a button without any text, please?
- [x] - Also, if I change the colour of the button, it's not working 

![Image](https://github.com/user-attachments/assets/dea56293-cbf7-4e5a-8aaa-9d79392b1100)

- [ ] - Please, can we also have an option for a wider banner? At the moment, I can't set up the width of the banner
![Image](https://github.com/user-attachments/assets/e21d8344-b8c0-48b6-82b7-9718c63d6297)

**Comment by dandiAW** [comment]
Hi @AW-Martina , thank you in advance.

Alright, thank you for your request. I will work on the web block tasks one by one shortly. Please wait, and I will update you as soon as possible. Thank you.

**Comment by AW-Martina** [comment]
Thank you @dandiAW 

- [ ] One more request, can you please add a contact form for fulfilment, something similar as on screenshot? Thank you.

![Image](https://github.com/user-attachments/assets/60cc8b69-172e-4967-b418-29d31da9eb1f)

**Comment by dandiAW** [comment]
Hi @AW-Martina Certainly! I'm currently working on it. Please feel free to request it anytime if needed. Thank you!

**Comment by AW-Martina** [comment]
Thank you @dandiAW 
A few more things 

- [x] - font size 18px please, so it can be used across the whole website.
- [x] - possibility to place iframe in columns (e.g. left side text, right side iframe (map))
- [x] - CTA possibility to place text on the left side and button on the right (please see example on the picture)

- [x] ![Image](https://github.com/user-attachments/assets/4ee24b1b-2b47-4e93-a698-bd521a351661)

- [x] -new feature: Accordion dropdowns or simple collapsible blocks ( please see picture) 

- [x] ![Image](https://github.com/user-attachments/assets/b137636e-01c6-4917-9dd7-67bbd3d4d7d1)

- [x] possibility to have two columns for registration - text left side and form right side (as on the example picture)

- [x] ![Image](https://github.com/user-attachments/assets/dbcca0ce-0004-4ef0-b57c-7de44654cba7)

- [x] More icons available in the menu bar suitable for fulfilment, please also possibility to not choose an icon on the menu bar.

- [x] ![Image](https://github.com/user-attachments/assets/450752f7-f0ea-4ba1-b601-b65df0cb9a3e)

- [x] Can there be an option to choose whether I want a shadow under the CTA block or not? 

- [x] ![Image](https://github.com/user-attachments/assets/65cd4302-02f0-4ed6-be3c-38993286c1b9)

- [x] adding block with timeline (something similar as on the example picture)

- [x] ![Image](https://github.com/user-attachments/assets/07977d09-df34-47d6-847c-cc9d341ad882)

- [ ] when changing the font for italic it change the font type family from Ralway to Sans-serif


- [ ] ![Image](https://github.com/user-attachments/assets/09a2fb72-deb7-43d3-9401-000b13d99f3e)

**Comment by dandiAW** [comment]
Hello @AW-Martina , thank you for your request. If there's anything else like new block or new feature for our web block, please feel free to write it here so I can address them one by one. I am currently working on all your requests. Thank you!

**Comment by YudhistiraA** [comment]
Hi @AW-Martina 👋

Just a quick update — I’ve completed several of your recent requests.

To create a 2-column layout, you can now use the "Block Column Layout 2" as shown in the screenshots below:

![Image](https://github.com/user-attachments/assets/9e29d9b5-fb2f-45ed-bb21-78fba28fd000)

![Image](https://github.com/user-attachments/assets/7dea742c-c554-4498-9249-f8ad894d227d)

![Image](https://github.com/user-attachments/assets/d4ac8204-091f-48b0-ba2c-b68497580614)

I’d recommend using blocks that contain only one component — such as text, button, or disclosure — for the cleanest and most manageable layout.

---


For the menu icons, could you let me know which icons you'd like to use for:
- Menu Fulfillment
- Menu Dropshipping

You can browse and choose from the icon library here:
👉 [Font Awesome v5 Icon List](https://fontawesome.com/v5/search)

Just send me the names of the icons you prefer, and I’ll get them added for you right away.

---

For the remaining changes, the implementation follows a similar pattern to what we’ve done before. Once you've had a chance to review, feel free to confirm the items that are ✅ so I can officially mark them as done.

As for the dropshipping website, we’ll begin development tomorrow. Ideally, I’d love for you to start testing it either tomorrow or Friday.


Best regards,
Arya

**Comment by AW-Martina** [comment]
Thank you @YudhistiraA 
Just a couple more things :) Thank you in advance.

- [x] The background colour not changing in the collumn-layout-2 please see the image:

![Image](https://github.com/user-attachments/assets/f08841a4-e557-4eb7-a324-8cd5b9f671fe)

- [x] Collumn-layout-2 when inserting a link to a picture is not working, it shows me in Aiku that there is a link, but on the published website, the is no link

![Image](https://github.com/user-attachments/assets/f1c1190c-7d6b-498d-b900-95521ef6d70d)

- [ ] **Can it be possible to align the picture in the centre of the text, and also, would it be great to be able to set the size of the picture in px so I can be sure all the pictures are the same size? As if I am resizing it just with the mouse, then some pictures may be slightly bigger than others, and then, when published, it shows differently on the website than in Aiku. All pictures and text are aligned the same, but the last picture is pushed to the left on the website, as I guess it was slightly bigger. Please see the picture:** @YudhistiraA Please, can this be fixed ASAP?

![Image](https://github.com/user-attachments/assets/8a3471fc-3f7f-431a-8d80-960a4fc6f30f)

- [ ] Can we have this future possible on webiste. When hover over with mouse it slide and reveal the other text. Like on video:


https://github.com/user-attachments/assets/927442c5-2dfc-42a0-a4f5-eb6b1b6e75fd

- [ ] also possiblity to outpaly video directly on the webiste same as on this video from AW Advantage website:


https://github.com/user-attachments/assets/da03707f-6d02-4423-98ae-8cc069c456b9

- [ ] Would it be possible to have menu bar in the same level as logo ? also with CTA button same as on AW Advantage website or Totalfulfilment website? 


![Image](https://github.com/user-attachments/assets/bf83878f-c80a-4ca4-97c8-f8987cbddbe8)
![Image](https://github.com/user-attachments/assets/29504c9a-1a2c-423a-bb23-3a53a267df3b)

- [ ] New future: counting banner same as on AW Advantage: 

https://github.com/user-attachments/assets/f9121708-4c7f-4fe2-b650-531c769b2a3e

- [ ] collumn-layout-2 can't see all options for editing text:

![Image](https://github.com/user-attachments/assets/3e40690a-1af9-4e33-a271-c93bbc03c10d)

- [x] Option to add gradient background please

![Image](https://github.com/user-attachments/assets/3b9c84d0-127b-44dd-9a1b-ee6d9c32c062)

- [ ] Option to have this kind of layout (I tried to create something similar (please see pic 2), but I can't have two blocks under each other and also cant align the button on the left side):

![Image](https://github.com/user-attachments/assets/52144e88-5b46-4bd5-ab5e-4e55b3b22c72)

![Image](https://github.com/user-attachments/assets/ebefdec5-5c2b-43a3-91d2-9cb2088d735e)


Thank you
Martina

**Comment by aqordeon** [comment]
Hello @AW-Martina 👋, here's some updates so far:
- [x] The background colour not changing in the collumn-layout-2
- [x] collumn-layout-2 can't see all options for editing text
- [x] Collumn-layout-2 when inserting a link to a picture is not working, it shows me in Aiku that there is a link, but on the published website, the is no link

We will finish your request as soon as possible🙂

**Comment by AW-Martina** [comment]
Hi @YudhistiraA ,
Thank you for the update. I am experiencing issues again with a few things which was previously fixed, such as:
- [x] can't upload the pictures, I select the image upload it but the the picture not showing

![Image](https://github.com/user-attachments/assets/0cdba606-12fb-44e9-8b09-03fd0eb4264e)

- [ ] text box, if I add a picture into the text box, it is again above the text, not in the same line :

![Image](https://github.com/user-attachments/assets/d6c1ffc9-dd11-4bc7-ad45-953113ae6c61)

- [x] The gap between columns is not changing; it doesn't matter what number I put, the gap remains the same:

![Image](https://github.com/user-attachments/assets/afdae316-ecf3-4b0e-9ad3-1650258e96ca)

- [x] The font size 18px disappears:

![Image](https://github.com/user-attachments/assets/128df8e5-e105-42de-baf4-0448b490bf32)


- [x] I picked some icons from the website you provided. Can we have the following icons for now, please:
- https://fontawesome.com/v5/icons/truck-loading?f=classic&s=regular
- https://fontawesome.com/v5/icons/truck-moving?f=classic&s=regular
- https://fontawesome.com/v5/icons/truck-container?f=classic&s=regular
- https://fontawesome.com/v5/icons/user?f=classic&s=regular
- https://fontawesome.com/v5/icons/warehouse?f=classic&s=regular
- https://fontawesome.com/v5/icons/warehouse-alt?f=classic&s=regular
- https://fontawesome.com/v5/icons/shipping-fast?f=classic&s=regular
- https://fontawesome.com/v5/icons/inventory?f=classic&s=regular
- https://fontawesome.com/v5/icons/dolly-flatbed-alt?f=classic&s=regular
- https://fontawesome.com/v5/icons/boxes?f=classic&s=regular
- https://fontawesome.com/v5/icons/shopping-cart?f=classic&s=regular
- https://fontawesome.com/v5/icons/badge-percent?f=classic&s=regular
- https://fontawesome.com/v5/icons/chevron-right?f=classic&s=regular
- https://fontawesome.com/v5/icons/caret-right?f=classic&s=regular
- https://fontawesome.com/v5/icons/phone-alt?f=classic&s=regular
- https://fontawesome.com/v5/icons/globe?f=classic&s=regular
- https://fontawesome.com/v5/icons/percent?f=classic&s=regular
- https://fontawesome.com/v5/icons/pound-sign?f=classic&s=regular
- https://fontawesome.com/v5/icons/clock?f=classic&s=regular

Thank you
Martina

**Comment by AW-Martina** [comment]
Hi @YudhistiraA 
- [ ] Also, I  would like to request a new feature: a simple pricing calculator, such as here: https://tspfulfilment.co.uk/pricing


Thank you 
Martina

**Comment by aqordeon** [comment]
Hello @AW-Martina , what data of the pricing calculator you needed?
- Average number of orders per month
- Average number of items per order
- Average order weight

is it just that 3?

**Comment by aqordeon** [comment]
Hello @AW-Martina 👋, here's another update:
- [x] Background gradient color
- [x] Table color background & color border
- [x] Font size 18px

**Comment by AW-Martina** [comment]
> Hello [@AW-Martina](https://github.com/AW-Martina) , what data of the pricing calculator you needed?
> 
> * Average number of orders per month
> * Average number of items per order
> * Average order weight
> 
> is it just that 3?

Hello @YudhistiraA Yes, this is all we need :) thank you

**Comment by AW-Martina** [comment]
Hi @YudhistiraA 

- [ ] I just found another issue. When I choose background colour and add padding then it make the background colour for padding area lighter, please, see screenshot:

![Image](https://github.com/user-attachments/assets/33cf78dd-effa-4e22-a2b1-a08dcd0f5d42)

**Comment by AW-Martina** [comment]
Hello @YudhistiraA 

Few more things what I found that are not working:

- [x] Logo and the text disappeared from header and I cant edit header - Cant upload logo 

![Image](https://github.com/user-attachments/assets/8b82d1cf-c7c3-4212-bbbb-bacf8883665e)

![Image](https://github.com/user-attachments/assets/6a9b533c-e646-4322-a497-d8a0dbe155c2)

**Comment by AW-Martina** [comment]
Hi @YudhistiraA 

- [ ] I want to request another feature: tabbed layout, something like below (possibility to add text or pictures into the tab, please):

![Image](https://github.com/user-attachments/assets/914a1db8-bf0f-4bd4-bda5-f71a8ec4d3e0)

Thank you
Martina

**Comment by AW-Martina** [comment]
Hi @YudhistiraA ,
I have a couple of issues again, please can this be done ASAP, I need this to finish the storefront page:

- [x] Pictures are not uploading; they remain pending, and nothing happens.

![Image](https://github.com/user-attachments/assets/403b2d34-7793-4996-a129-b1d33f077bff)

- [ ] ![Image](https://github.com/user-attachments/assets/3633e638-e387-4c5a-8ef9-eeaf0dff469b)

- [x] Possibility to adjust the width of the blog text on the CTA with image so the scroll bar would disappear, and also the width of the CTA
![Image](https://github.com/user-attachments/assets/77b05f47-1f51-414e-b9e2-9aec715027b0)

- [x] Timeline - possibility to change the section with numbers (colour) and also possibility to change numbers for text, icons or even small pictures
![Image](https://github.com/user-attachments/assets/78f0eb0f-31f0-43f5-9a10-0aa06291ea1b)


- [x] When changing the background for a picture, the background remains white:

![Image](https://github.com/user-attachments/assets/29f9ccf6-53db-4983-b190-f2a6e3d21ead)

- [x] Pricing blog:

Once published, it shows characters that are supposed not to be visible and does not show the button. Also, can you at least for now change the ticks colour to this colour (#C1A027) so it matches branding :

![Image](https://github.com/user-attachments/assets/248195ec-853d-4594-bf59-f27ab023e737)
![Image](https://github.com/user-attachments/assets/0b589547-9d37-4d63-b0e2-f8f79b86734c)

Thank you 
Martina

**Comment by YudhistiraA** [comment]
Hello @AW-Martina,

I’ve made some updates to your previous issue and also introduced a new feature that allows you to edit the layout specifically for mobile view.

![Image](https://github.com/user-attachments/assets/1c6766bf-c3d3-4ace-9934-cd71e848e916)

At the moment, this feature is only available for a few blocks — particularly the CTA with Image component.
I’d appreciate it if you could take a moment to test it and share your feedback.

Best regards,
Arya

**Comment by AW-Martina** [comment]
Hi @YudhistiraA ,
Thank you for the update.
I’ve been adjusting the mobile view—specifically the storefront CTA with the image at the top. While I can resize the block itself, the text doesn’t scale responsively. It looks oversized on mobile, and when I try to reduce the font size manually, it affects the desktop version as well.

- [ ] Would it be possible to use CSS clamp() for font sizes instead of fixed units like pixels? That way, the text can scale more intelligently across different screen sizes, which I believe is better aligned with modern responsive design.

- [ ] Also, I have again a problem that I can't edit this text on the homepage:

![Image](https://github.com/user-attachments/assets/b423ddf6-6d48-4e30-a181-45998d266147)

Thank you 
Martina

**Comment by AW-Martina** [comment]
Hi @YudhistiraA ,
I'm just checking the project tracker, and I'm supposed to edit also Registration page and the customer's profile account but I don't have access to this.

![Image](https://github.com/user-attachments/assets/48ad2f49-24af-421b-9a5f-01d57fab925d)

Can I get the access, please?
Thank you 
Martina

**Comment by YudhistiraA** [comment]
Hello @AW-Martina 

We've granted you access to edit the project tracker.

I've also updated the timeline section — it's now called "Step". This new format is simpler and more flexible than the previous timeline, and it allows you to add icons for better visual clarity.


Best regards,
Arya

**Comment by AW-Martina** [comment]
Hi @YudhistiraA, 
Thank you for the quick reply & update (I will try timeline tomorrow)
Sorry for the confusion, I didn't mean access to the project tracker, but access to modify the registration page and customer profile account. The registration page and customer profile account are created in a third-party app (I think Envato??)  to which I don't have access.

As you can see, the page is very blank without a logo:  
![Image](https://github.com/user-attachments/assets/7f063e9d-4440-47bb-a8c1-5cffec43aab0)
I would like to create something like this, with a logo linked to the homepage, a login button, and also some text next to the registration form:
![Image](https://github.com/user-attachments/assets/aaa367f7-e508-4560-a2f2-e08c06f146eb)

Same, the login page is missing the logo and possibly the button for registration (something like ShipStation has - second screenshot):
![Image](https://github.com/user-attachments/assets/ca65f469-f784-4137-acdf-9e45005b666a)
![Image](https://github.com/user-attachments/assets/e5e812d9-5006-4ad6-9a80-4d8aee9c4af4)

Thank you 
Martina

**Comment by YudhistiraA** [comment]
Hello @AW-Martina,

I've added the Header and Footer to both the login and register pages.

You can check them here:
🔐 Login: https://www.aw-fulfilment.co.uk/app/login
📝 Register: https://www.aw-fulfilment.co.uk/app/register

At this stage, integrating the login and registration into the Workshop as you want is a bit challenging, as we don’t yet have a finalized design for the forms. For now, we've implemented them manually to ensure progress.

We’ll document this in the developer notes so it can be properly handled and improved during the Workshop development phase.

Best regards,
Arya

**Comment by AW-Martina** [comment]
Hi @YudhistiraA 

Ok thank you. It looks much better. Just one more thing, can you change the colour of the button to the brand colour #C1A027

![Image](https://github.com/user-attachments/assets/c21a304d-bc07-4a8d-aece-f7bb97b678d0)

Thank you 
Martina

**Comment by AW-Martina** [comment]
Hello Arya,

- [x] Please, can you change the colour of the login button ASAP is white white with white text at the moment, please see picture below:

![Image](https://github.com/user-attachments/assets/ad8bdb0d-ac82-46de-bb7e-75052d6c7ced)

**Comment by YudhistiraA** [comment]
Hello @AW-Martina,

sorry for the mistake, we have fixed it
You can check them here:
🔐 Login: https://www.aw-fulfilment.co.uk/app/login
📝 Register: https://www.aw-fulfilment.co.uk/app/register

Best regards,
Arya

**Comment by AW-Martina** [comment]
Hello Arya,

Thank you very much. 

A few more issues:

- [x] I still have a problem with the pricing blog, the buttons still don't show, and I can't upload icons/pictures :

![Image](https://github.com/user-attachments/assets/e2ab89db-ccb5-421b-800d-14291dc2624b)
![Image](https://github.com/user-attachments/assets/3110669c-a2e9-44e3-92ef-b5535e8e8260)

- [ ] ![Image](https://github.com/user-attachments/assets/107d7461-60a6-4c0b-aae1-b469f3c6bb94)

**Comment by AW-Martina** [comment]
Hi Arya,

I would like to ask about the Contact Us form. You said you are working on it, and I would like to know what stage it is at the moment?🙂 I temporarily created one in Google Sheets and added it to a website as an iframe. Not ideal, but for now it will work. 

![Image](https://github.com/user-attachments/assets/9240cc07-472d-4399-83e4-9446163a99fd)

I tried Timeline (Step). It works good, so far I only had one issue - the gradient background not working in aiku. Once published, I can see the background, but it changes the line colour, and also the background is not the full width of the page.

- [x] ![Image](https://github.com/user-attachments/assets/2bd03b85-ab38-4dcd-99cc-c39bbd48b339)

![Image](https://github.com/user-attachments/assets/dd7ffb96-73c3-4e41-aadd-2f0c5ac5b481)

Also, pricing blog could it be possible to align the text in the pricing blog to the top instead of to the centre?

![Image](https://github.com/user-attachments/assets/23e06356-ee2c-4db2-8896-9f2247d2edee)

I tried to upload the picture to the pricing blog, but it's not working. It allows me to pick the picture 

https://github.com/user-attachments/assets/4aadf790-f87b-4d90-90b2-4f73e35c6e53

![Image](https://github.com/user-attachments/assets/28b7c11b-99fd-4bd0-91e8-28146e4fcb7f)

Can you please have a look?
Thank you 
Martina

**Comment by dandiAW** [comment]
![Image](https://github.com/user-attachments/assets/80ffeba7-e689-4e05-90c7-8a58dfef1a5c)
Hi @AW-Martina 
I apologize for the error you encountered in the pricing block. I’ve fixed the image-upload functionality there, but you’ll need to recreate the pricing block from scratch since the old one didn’t include an image. I’m sorry for the extra work—once you rebuild it, the image should appear correctly.

I’ve tested the image upload myself, and it now displays successfully. Please try creating a new pricing block again. thank you :)

Best regards,
Dandi

**Comment by AW-Martina** [comment]
Hi @dandiAW 

- [x] Thank you for your quick response. So I re-created the pricing blog as you advised; however, the text under the title does not change when published, and I am unable to align the text title of the middle tab. Also, would it be possible to set the picture size in px in the Aiku, please?

- [ ] 

![Image](https://github.com/user-attachments/assets/bc26f9bc-ea3d-4301-8b50-cb82f23b2086)
![Image](https://github.com/user-attachments/assets/d3a313b5-bd6e-49ad-924e-5b993b090dc5)

https://github.com/user-attachments/assets/faf24108-3062-4734-8065-a16b94efdfa2

**Comment by AW-Martina** [comment]
Hello again :) 

Can I ask why the website is not full-width as it was yesterday? Now all pages look bad 😅

![Image](https://github.com/user-attachments/assets/e11c0337-4638-4a77-a5af-92ba5336ae04)
![Image](https://github.com/user-attachments/assets/3ef3aa05-790e-47e3-ad97-ad59c332d534)

**Comment by YudhistiraA** [comment]
Hi @AW-Martina ,

Apologies for the confusion earlier — we’ve made quite a few changes on our side after receiving Thomas’s feedback.

The issue with the font size has been addressed, and we've now implemented the responsive font sizing update. That said, I’d appreciate it if you could take another look to ensure everything is functioning correctly. If anything still seems off, feel free to adjust the font sizes again.

Sorry again for adding to your workload, and thank you for your patience!

Best regards,
Arya

**Comment by AW-Martina** [comment]
Good morning. 
Thank you, it's back to normal now 😃
Would it be possible to have a button on the top of the page instead of this text?:

- [x] ![Image](https://github.com/user-attachments/assets/a741fb23-68dc-498f-a110-58d1a35ab88c)

Also, I am still not able to align the picture in the text box in line with the text. Can you please fix it?

- [ ] ![Image](https://github.com/user-attachments/assets/9b0c5cec-2b35-4cec-8f48-43a0c86cc740)

Thank you 
Martina

**Comment by YudhistiraA** [comment]
Hi @AW-Martina,

Please try using Template Header 1 as shown below:

![Image](https://github.com/user-attachments/assets/6fcc8606-b08d-4b6d-8b4e-468ee011b27c)

To fix the layout on mobile devices, make sure to review and apply proper padding and margin settings for mobile breakpoints — I've already added them throughout:

![Image](https://github.com/user-attachments/assets/d1b48433-9fdf-4d53-8074-75f64c37e4a5)

![Image](https://github.com/user-attachments/assets/9af4baf7-8b0d-42e2-a4e4-0af7bf7dc19d)


Let me know if everything looks good or if you’d like me to fine-tune anything.

Best regards,
Arya

**Comment by AW-Martina** [comment]
Hi @Arya. 
Thank you,  Header 1 is working :) 
There is just a small issue I am not seeing in Aiku what I am doing 😅

![Image](https://github.com/user-attachments/assets/6a423fed-339f-43ca-a067-1016e7fbf8a1)

And I can align the text in the button to the middle. It's on the left side by default.

![Image](https://github.com/user-attachments/assets/a86e49c4-19c1-4fb2-ad9b-c5c75c33e241)

Also its linked but its not working.

I've seen you add a mobile layout. I have one more page to create, and then I will go back to all pages and adjust them one by one to mobile.  
Thank you
Martina

**Comment by AW-Martina** [comment]
Hello again. 
Would it be possible to freeze the header and menu so it's always visible on the page, even when scrolled down? Something like on totalfulfilment page:

- [ ] https://github.com/user-attachments/assets/461602ca-b4d3-4633-9944-43eee7d898e6

Thank you 
Martina

**Comment by YudhistiraA** [comment]
hello @AW-Martina 

![Image](https://github.com/user-attachments/assets/5dcdd901-9bfc-4e18-87fb-fa8b77584e2e)
i fix it for you 

Best regards,
Arya

**Comment by AW-Martina** [comment]
Thank you @Arya

**Comment by AW-Martina** [comment]
@Arya, the link in the button is still not working, can you please have a look?
Thank you 
Martina

**Comment by AW-Martina** [comment]
Also, I have now problem with collum-layout-2 I have only these few options to choose from :

![Image](https://github.com/user-attachments/assets/3468acf1-b7a8-4913-8a38-276615151a9f)

**Comment by YudhistiraA** [comment]
Hello @AW-Martina,

I've fixed the button header.

As for the 2-column layout, I'm currently improving its appearance on mobile — since elements like the CTA and text columns don’t look good in the current setup. I’m adjusting them step by step and will reintroduce everything into the improved version once it's ready.

Estimated completion: by tomorrow.

Best regards,
Arya

**Comment by AW-Martina** [comment]
No problem Arya, thank you very much for the update.

**Comment by AW-Martina** [comment]
Hi Arya. Any updates, please?
